<?php
/**
 * Created by PhpStorm.
 * User: IT_PTSP
 * Date: 2/24/2017
 * Time: 2:01 PM
 */

namespace App\Models\Banners;
use App\Repositories\BaseRepository;

class EloquentBanner extends BaseRepository implements BannerRepository
{
    public function __construct(Banner $banner)
    {
        $this->model = $banner;
    }

    public function storeData($attributes)
    {
        return parent::storeData($attributes); // TODO: Change the autogenerated stub
    }
    public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }

    public function updateById($id, $data)
    {
        return parent::updateById($id, $data); // TODO: Change the autogenerated stub
    }

    /**
     * Created by : BillJanny
     * Date: 2:21 PM - 2/24/2017
     * Lấy danh sách banner in ra table
     * @param array $filter : mang filter
     * @param array $sort : mang sap xep
     * @param int $limit : giới hạn trên một trang
     * @return mixed
     */
    public function getListAll($filter = array(), $sorts = array(), $limit = 30)
    {
        $query = $this->model->whereRaw(1);
        // Loc thong tin
        $this->scopeFilter($query, $filter);

        // scope data get admin
        $this->scopeInforAdmin($query);

        // scope sap xep
        $this->scopeSort($query, $sorts);

        return $query->paginate($limit);
    }

    public function updateByField($id, $field, $otherValue = '')
    {
        return parent::updateByField($id, $field, $otherValue);
    }
}