<?php

use Illuminate\Database\Seeder;

class Category extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $category = [
            'Bữa ăn của tôi' => [
                'Khai vị',
                'Tráng miệng',
                'Bữa sáng',
                'Bữa tối',
                'Bữa trưa',
            ],
            'Đồ uống' => [
                'Sinh tố',
                'Chè',
                'kem & sữa chua',
            ],
            'Thành phần' => [
                'Thịt gà',
                'Cá',
                'Thịt bò',
                'Thịt lợn',
                'Khác'
            ],
            'Dịp nấu' => [
                'Sinh nhật',
                'Hàng ngày',
                'Năm mới',
                'Giáng sinh',
            ],
            'Ẩm thực vùng miền' => [
                'Bắc (Việt Nam)',
                'Trung (Việt Nam)',
                'Nam',
                'Nhật bản',
                'Thái lan',
                'Singapor',
                'Hàn quốc',
                'Khác'
            ],
            'Cẩm nang ẩm thực' => [
                'kinh nghiệm nấu ăn',
                'Thực phẩm an toàn',
                'Bộ sưu tập món ăn',
                'Bảo quản thực phẩm',
                'Sức khỏe dinh dưỡng',
                'Mẹo vặt',
                'Thực đơn giảm cân',
                'Thực đơn giàu dinh dưỡng'
            ],
            'Chia sẻ hay' => [
                'Thực phẩm sạch',
                'Nước chấm',
                'Món canh',
                'Địa điểm ăn uống',
                'Bộ sưu tập món ăn'
            ],
            'Phong cách nấu' => [
                'Nhanh và dễ làm',
                'Kho',
                'Xào',
                'Nướng',
                'Hầm',
                'Chiên',
                'Khác'
            ]
        ];

        $categories = [
            [
                'cate_name' => 'Bữa ăn của tôi',
                'cate_meta_title' => 'Bữa ăn của tôi',
                'cate_meta_keyword' => 'Bữa ăn của tôi',
                'cate_meta_description'=> 'Bữa ăn của tôi',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 0,
                'cate_has_child' => 1,
                'cate_all_child' => '1, 2, 3, 4, 5, 6'
            ],
            [
                'cate_name' => 'Khai vị',
                'cate_meta_title' => 'Khai vị',
                'cate_meta_keyword' => 'Khai vị',
                'cate_meta_description'=> 'Khai vị',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 1,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Tráng miệng',
                'cate_meta_title' => 'Tráng miệng',
                'cate_meta_keyword' => 'Tráng miệng',
                'cate_meta_description'=> 'Tráng miệng',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 1,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Bữa sáng',
                'cate_meta_title' => 'Bữa sáng',
                'cate_meta_keyword' => 'Bữa sáng',
                'cate_meta_description'=> 'Bữa sáng',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 1,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Bữa tối',
                'cate_meta_title' => 'Bữa tối',
                'cate_meta_keyword' => 'Bữa tối',
                'cate_meta_description'=> 'Bữa tối',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 1,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Bữa trưa',
                'cate_meta_title' => 'Bữa trưa',
                'cate_meta_keyword' => 'Bữa trưa',
                'cate_meta_description'=> 'Bữa trưa',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 1,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Đồ uống',
                'cate_meta_title' => 'Đồ uống',
                'cate_meta_keyword' => 'Đồ uống',
                'cate_meta_description'=> 'Đồ uống',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 0,
                'cate_has_child' => 1,
                'cate_all_child' => '7, 8, 9, 10'
            ],
            [
                'cate_name' => 'Sinh to',
                'cate_meta_title' => 'Sinh to',
                'cate_meta_keyword' => 'Sinh to',
                'cate_meta_description'=> 'Sinh to',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 7,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Che',
                'cate_meta_title' => 'Che',
                'cate_meta_keyword' => 'Che',
                'cate_meta_description'=> 'Che',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 7,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Sua chua',
                'cate_meta_title' => 'Sua chua',
                'cate_meta_keyword' => 'Sua chua',
                'cate_meta_description'=> 'Sua chua',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 7,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Thanh phan',
                'cate_meta_title' => 'Thanh phan',
                'cate_meta_keyword' => 'Thanh phan',
                'cate_meta_description'=> 'Thanh phan',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 0,
                'cate_has_child' => 1,
                'cate_all_child' => '11, 12, 13, 14'
            ],
            [
                'cate_name' => 'thit ga',
                'cate_meta_title' => 'thit ga',
                'cate_meta_keyword' => 'thit ga',
                'cate_meta_description'=> 'thit ga',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 11,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Ca',
                'cate_meta_title' => 'Ca',
                'cate_meta_keyword' => 'Ca',
                'cate_meta_description'=> 'Ca',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 11,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Thit lon',
                'cate_meta_title' => 'Thit lon',
                'cate_meta_keyword' => 'Thit lon',
                'cate_meta_description'=> 'Thit lon',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 11,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Dịp nấu',
                'cate_meta_title' => 'Dịp nấu',
                'cate_meta_keyword' => 'Dịp nấu',
                'cate_meta_description'=> 'Dịp nấu',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 0,
                'cate_has_child' => 1,
                'cate_all_child' => '16, 17, 18, 19'
            ],
            [
                'cate_name' => 'Sinh nhật',
                'cate_meta_title' => 'Sinh nhật',
                'cate_meta_keyword' => 'Sinh nhật',
                'cate_meta_description'=> 'Sinh nhật',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 15,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Hang ngay',
                'cate_meta_title' => 'Hang ngay',
                'cate_meta_keyword' => 'Hang ngay',
                'cate_meta_description'=> 'Hang ngay',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 15,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Nam moi',
                'cate_meta_title' => 'Nam moi',
                'cate_meta_keyword' => 'Nam moi',
                'cate_meta_description'=> 'Nam moi',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 15,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Giang sinh',
                'cate_meta_title' => 'Giang sinh',
                'cate_meta_keyword' => 'Giang sinh',
                'cate_meta_description'=> 'Giang sinh',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 15,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Ẩm thực vùng miền',
                'cate_meta_title' => 'Ẩm thực vùng miền',
                'cate_meta_keyword' => 'Ẩm thực vùng miền',
                'cate_meta_description'=> 'Ẩm thực vùng miền',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 0,
                'cate_has_child' => 1,
                'cate_all_child' => '20, 21, 22',
            ],
            [
                'cate_name' => 'Nhat ban',
                'cate_meta_title' => 'Nhat ban',
                'cate_meta_keyword' => 'Nhat ban',
                'cate_meta_description'=> 'Nhat ban',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 20,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Han quoc',
                'cate_meta_title' => 'Han quoc',
                'cate_meta_keyword' => 'Han quoc',
                'cate_meta_description'=> 'Han quoc',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 20,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Singapor',
                'cate_meta_title' => 'Singapor',
                'cate_meta_keyword' => 'Singapor',
                'cate_meta_description'=> 'Singapor',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 20,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Cẩm nang ẩm thực',
                'cate_meta_title' => 'Cẩm nang ẩm thực',
                'cate_meta_keyword' => 'Cẩm nang ẩm thực',
                'cate_meta_description'=> 'Cẩm nang ẩm thực',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 0,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Chia sẻ hay',
                'cate_meta_title' => 'Chia sẻ hay',
                'cate_meta_keyword' => 'Chia sẻ hay',
                'cate_meta_description'=> 'Chia sẻ hay',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 0,
                'cate_has_child' => 0,
            ],
            [
                'cate_name' => 'Phong cách nấu',
                'cate_meta_title' => 'Phong cách nấu',
                'cate_meta_keyword' => 'Phong cách nấu',
                'cate_meta_description'=> 'Phong cách nấu',
                'cate_type' => 'news',
                'cate_picture' => '/media/news/new.jpg',
                'cate_admin_id' => 1,
                'cate_parent_id' => 0,
                'cate_has_child' => 0,
            ],
        ];

        foreach ($categories as $category)
        {
            \App\Models\Categories\Category::create($category);
        }
    }

    
}
