<?php
/**
 * Created by PhpStorm.
 * User: hung
 * Date: 21/01/17
 * Time: 12:12
 */
if (! function_exists('get_domain'))
{
    function get_domain()
    {
        return [
//            [
//                'cd_domain'                => 'http://giadinh.net.vn',
//                'cd_law_crawl_link'        => '.listtotal .showlist li a|.listtotal .showlist li h4 a|.content-total .listhltoptotal .listhltop1 h2 a|.content-total .listhltoptotal .listhltop3 h3 a|.content-total .listhltoptotal .listhltop4 li h3 a',
//                'cd_add_domain_crawl_link' => '0',
//                'cd_law_title'             => 'h1',
//                'cd_law_description'       => '',
//                'cd_law_content'           => '#divNewsContent',
//                'cd_law_img'               => '',
//                'cd_law_remove'            => 'center|#loadContentRight|#advMidContent|iframe|script',
//                'cd_law_add_page'          => '/trang-{PAGE}.htm',
//                'cd_status'                => '1',
//                'cd_type'                  => '1',
//            ],
//            [
//                'cd_domain'                => 'http://xahoi.com.vn',
//                'cd_law_crawl_link'        => '.tit-tinnoibat h2 a|.tit-noibat-cm h3 a',
//                'cd_add_domain_crawl_link' => '0',
//                'cd_law_title'             => 'h1',
//                'cd_law_description'       => '',
//                'cd_law_content'           => '.row-main-ct-top .col-md-7 .row-chitiet',
//                'cd_law_img'               => '',
//                'cd_law_remove'            => 'center|link|.adsbygoogle|iframe|div|script|style',
//                'cd_law_add_page'          => '/trang-{PAGE}',
//                'cd_status'                => '1',
//                'cd_type'                  => '1',
//            ],
//            [
//                'cd_domain'                => 'http://www.vietgiaitri.com',
//                'cd_law_crawl_link'        => '.post-content-archive h2 a|.post-content-archive h3 a',
//                'cd_add_domain_crawl_link' => '1',
//                'cd_law_title'             => 'h1',
//                'cd_law_description'       => '',
//                'cd_law_content'           => '.post-content',
//                'cd_law_img'               => '',
//                'cd_law_remove'            => 'center|link|#LeftPost|#aka_banner|script|style|#inpage',
//                'cd_law_add_page'          => '/page/{PAGE}/',
//                'cd_status'                => '1',
//                'cd_type'                  => '1',
//            ],
//                [
//                    'cd_domain'                => 'http://afamily.vn',
//                    'cd_law_crawl_link'        => '.sub_hotct fl h2 a|.sub_hotct2 li h3 a|.box-x3 h4 a|.box-x2 a',
//                    'cd_add_domain_crawl_link' => '1',
//                    'cd_law_title'             => 'h1',
//                    'cd_law_description'       => '',
//                    'cd_law_content'           => '.af-detailmain-2',
//                    'cd_law_img'               => '',
//                    'cd_law_remove'            => 'center|link|script|style|.social-bottom|.share-top|.detail_other|#breadCrumb',
//                    'cd_law_add_page'          => '/trang-{PAGE}.chn',
//                    'cd_status'                => '1',
//                    'cd_type'                  => '1',
//                ],
//                [
//                    'cd_domain'                => 'https://giadinh.tv',
//                    'cd_law_crawl_link'        => '.entry-header h3 a',
//                    'cd_add_domain_crawl_link' => '0',
//                    'cd_law_title'             => 'h1',
//                    'cd_law_description'       => '',
//                    'cd_law_content'           => '#main-content',
//                    'cd_law_img'               => '',
//                    'cd_law_remove'            => 'center|link|script|style|.center-ads|.breadcrumbs|.entry-meta|.nc_socialPanel|.swp-content-locator|.adsbygoogle',
//                    'cd_law_add_page'          => '/page/{PAGE}/',
//                    'cd_status'                => '1',
//                    'cd_type'                  => '1',
//                ],
//                   [
//                        'cd_domain'                => 'http://www.phunutoday.vn',
//                        'cd_law_crawl_link'        => 'article .news_info h3 a|.m_hot article h1 a|.n_other article h2 a',
//                        'cd_add_domain_crawl_link' => '0',
//                        'cd_law_title'             => 'h1',
//                        'cd_law_description'       => '',
//                        'cd_law_content'           => '.details',
//                        'cd_law_img'               => '',
//                        'cd_law_remove'            => 'center|link|script|style|.social_top|.social_bottom|.d_main_right|time
//                                            |.list_suggest_link|.adsbygoogle|.list_suggest_desk|.adv|.n_list_update|.tags',
//                        'cd_law_add_page'          => '/p{PAGE}',
//                        'cd_status'                => '1',
//                        'cd_type'                  => '1',
//                    ],
//                    [
//                        'cd_domain'                => 'http://www.nauanngon123.com',
//                        'cd_law_crawl_link'        => 'table tbody tr td a',
//                        'cd_add_domain_crawl_link' => '0',
//                        'cd_law_title'             => 'h1',
//                        'cd_law_description'       => 'meta[name=description]',
//                        'cd_law_content'           => '.content',
//                        'cd_law_img'               => 'link[rel=image_src]',
//                        'cd_law_remove'            => 'center|link|script|style|.googlepublisherpluginad|.bottomcontainerBox|fb:comments|fb:comments-count|.breadcrumbs|.kk-star-ratings',
//                        'cd_law_add_page'          => '/p{PAGE}',
//                        'cd_status'                => '1',
//                        'cd_type'                  => '1',
//                    ],
//                        [
//                            'cd_domain'                => 'http://webgiadinh.org',
//                            'cd_law_crawl_link'        => '.item p strong a',
//                            'cd_add_domain_crawl_link' => '1',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => '',
//                            'cd_law_content'           => '.article',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle',
//                            'cd_law_add_page'          => '/?page={PAGE}',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                        ],
//                       [
//                            'cd_domain'                => 'http://yeunoitro.net/',
//                            'cd_law_crawl_link'        => '.item-new-ct-content .mh-42 a|.new-wp .w525 div a',
//                            'cd_add_domain_crawl_link' => '1',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => 'meta[name=description]',
//                            'cd_law_content'           => '#main .content-part',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle|.like-share-bt|.group-fb|.post-group-info|.breakumb|._fb',
//                            'cd_law_add_page'          => '/page/{PAGE}/',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                       ],
//                        [
//                            'cd_domain'                => 'http://sotaynauan.com/',
//                            'cd_law_crawl_link'        => 'article h3 a',
//                            'cd_add_domain_crawl_link' => '0',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => 'meta[name=description]',
//                            'cd_law_content'           => '.purerecipe',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle|.like-share-bt
//                                    |.group-fb|.flare-horizontal|.printfriendly|.fb-comments|.yarpp-related|.entry-utility|#author-data',
//                            'cd_law_add_page'          => '/page/{PAGE}/',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                       ],
//                         [
//                            'cd_domain'                => 'https://monan9.com',
//                            'cd_law_crawl_link'        => 'header h2 a',
//                            'cd_add_domain_crawl_link' => '0',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => 'meta[name=description]',
//                            'cd_law_content'           => 'article',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle|
//                                        .fcbk_share|#related-posts-via-taxonomies-title|.post-group-info|.breadcrumb|#related-posts-via-taxonomies-list|footer',
//                            'cd_law_add_page'          => '/page/{PAGE}/',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                       ],
//                        [
//                            'cd_domain'                => 'http://news.zing.vn',
//                            'cd_law_crawl_link'        => 'header p a',
//                            'cd_add_domain_crawl_link' => '1',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => '',
//                            'cd_law_content'           => '.main',
//                            'cd_law_img'               => 'meta[property=og:image:url]',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle|#mainContent_ctl00_divComment|.sidebar|
//                            #advVoteBar|#advArticleBottom|.the-article-tags|.the-article-share|.the-article-credit|.the-article-meta',
//                            'cd_law_add_page'          => '/trang{PAGE}.html',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                       ],
//                        [
//                            'cd_domain'                => 'https://agiadinh.net',
//                            'cd_law_crawl_link'        => '.news-summary h2 a',
//                            'cd_add_domain_crawl_link' => '0',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => '',
//                            'cd_law_content'           => '.blog-post',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle
//                                                |.kk-star-ratings|.yuzo_related_post|.post-tags|.fb-comments|meta|.mom-post-meta',
//                            'cd_law_add_page'          => '/page/{PAGE}',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                       ],
//                        [
//                            'cd_domain'                => 'http://mongingon.com',
//                            'cd_law_crawl_link'        => 'header h2 a',
//                            'cd_add_domain_crawl_link' => '0',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => '',
//                            'cd_law_content'           => '#content_box',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle
//                                                |.post-info|.breadcrumb|header .post-info|div a|iframe|.shareit|.thetags|.tabs|.related-posts',
//                            'cd_law_add_page'          => '/page/{PAGE}/',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                        ],
//                         [
//                            'cd_domain'                => 'http://cachnauan.net',
//                            'cd_law_crawl_link'        => 'article .content a[itemprop]',
//                            'cd_add_domain_crawl_link' => '0',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => '',
//                            'cd_law_content'           => 'article',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle|
//                                .post-meta|iframe|#MarketGidComposite78664|h3|ul|.post-share|p strong|.comments|#M201272ScriptRootC78664',
//                            'cd_law_add_page'          => '/page/{PAGE}',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                        ],
//                        [
//                            'cd_domain'                => 'https://nauankhongkho.com',
//                            'cd_law_crawl_link'        => '.entry-title a',
//                            'cd_add_domain_crawl_link' => '0',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => '',
//                            'cd_law_content'           => 'article',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle|
//                                .td-category|iframe|.td-module-meta-info|ul|footer',
//                            'cd_law_add_page'          => '/page/{PAGE}/',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                        ],
//                        [
//                            'cd_domain'                => 'http://tapchiamthuc.com',
//                            'cd_law_crawl_link'        => 'tr td .menu3|#table5 tr td .link100',
//                            'cd_add_domain_crawl_link' => '1',
//                            'cd_law_title'             => '#table3 tr td h2',
//                            'cd_law_description'       => 'meta[name=description]',
//                            'cd_law_content'           => '#table3',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle|
//                                #table5|#fb-root|.fb-comments|#table4',
//                            'cd_law_add_page'          => '{PAGE}_.html',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                        ],
//                         [
//                            'cd_domain'                => 'http://www.tapchigiadinh.com.vn',
//                            'cd_law_crawl_link'        => '.news h2 a',
//                            'cd_add_domain_crawl_link' => '1',
//                            'cd_law_title'             => 'h1',
//                            'cd_law_description'       => 'meta[name=description]',
//                            'cd_law_content'           => '.newsdetail',
//                            'cd_law_img'               => '',
//                            'cd_law_remove'            => 'center|link|script|style|fb:comments|fb:comments-count|.adsbygoogle|
//                                .fb-comments|#abd_vidinpage|.socialblock|#NewsTagsList|.date',
//                            'cd_law_add_page'          => '={PAGE}',
//                            'cd_status'                => '1',
//                            'cd_type'                  => '1',
//                        ],
//                            [
//                                'cd_domain'                => 'http://lambanh365.com',
//                                'cd_law_crawl_link'        => '.recipe-info-page li a',
//                                'cd_add_domain_crawl_link' => '0',
//                                'cd_law_title'             => 'h1',
//                                'cd_law_description'       => '',
//                                'cd_law_content'           => '.hrecipe',
//                                'cd_law_img'               => '',
//                                'cd_law_remove'            => 'center|link|script|style|.adsbygoogle|iframe|.thirdPartyRoot|.post-meta|.tips|.print-only|
//                                .content-right-first|.info-extra|#recipe-tabs|.embed|#shortcode_lien_quan',
//                                'cd_law_add_page'          => '/page/{PAGE}/',
//                                'cd_status'                => '1',
//                                'cd_type'                  => '1',
//                            ],
//                                [
//                                    'cd_domain'                => 'http://amthuchanoi.org',
//                                    'cd_law_crawl_link'        => '.entry-title a',
//                                    'cd_add_domain_crawl_link' => '0',
//                                    'cd_law_title'             => 'h1',
//                                    'cd_law_description'       => '',
//                                    'cd_law_content'           => '#entry-content',
//                                    'cd_law_img'               => '',
//                                    'cd_law_remove'            => 'center|link|script|style|.adsbygoogle|iframe|.td-category|.td-module-meta-info|.infinite-wrap|footer',
//                                    'cd_law_add_page'          => '/page/{PAGE}/',
//                                    'cd_status'                => '1',
//                                    'cd_type'                  => '1',
//                                ],
        ];
    }
}

if (! function_exists('get_domain_link'))
{
    function get_domain_link()
    {
        return [
//            [
//                'cdl_link'       => 'http://giadinh.net.vn/an.htm',
//                'cdl_domain_id'  => '1',
//                'cdl_check_page' => 0, // truong hop cho k can noi chuoi phan trang de lay du lieu
//                'cdl_cate_id'    => '0',
//                'cdl_page'       => '1',
//                'cdl_status'     => '1',
//            ],
//            [
//                'cdl_link'       => 'http://giadinh.net.vn/an',
//                'cdl_domain_id'  => '1',
//                'cdl_check_page' => 1,
//                'cdl_cate_id'    => '0',
//                'cdl_page'       => '10',
//                'cdl_status'     => '1',
//            ],
//            [
//                'cdl_link'       => 'http://xahoi.com.vn/du-lich-am-thuc/an-ngon-quan-xa',
//                'cdl_domain_id'  => '2',
//                'cdl_check_page' => 1,
//                'cdl_cate_id'    => '0',
//                'cdl_page'       => '27',
//                'cdl_status'     => '1',
//            ],
//                [
//                    'cdl_link'       => 'http://www.vietgiaitri.com/category/an-choi/am-thuc',
//                    'cdl_domain_id'  => '3',
//                    'cdl_check_page' => 1,
//                    'cdl_cate_id'    => '0',
//                    'cdl_page'       => '910',
//                    'cdl_status'     => '1',
//                ],
//                [
//                    'cdl_link'       => 'http://afamily.vn/an-ngon',
//                    'cdl_domain_id'  => '4',
//                    'cdl_check_page' => 1,
//                    'cdl_cate_id'    => '0',
//                    'cdl_page'       => '710',
//                    'cdl_status'     => '1',
//                ],
//                  [
//                    'cdl_link'       => 'https://giadinh.tv/nau-an',
//                    'cdl_domain_id'  => '5',
//                    'cdl_check_page' => 1,
//                    'cdl_cate_id'    => '0',
//                    'cdl_page'       => '41',
//                    'cdl_status'     => '1',
//                 ],
//                   [
//                    'cdl_link'       => 'http://www.phunutoday.vn/nau-an',
//                    'cdl_domain_id'  => '6',
//                    'cdl_check_page' => 1,
//                    'cdl_cate_id'    => '0',
//                    'cdl_page'       => '247',
//                    'cdl_status'     => '1',
//                  ],
//                   [
//                    'cdl_link'       => 'http://www.nauanngon123.com/nau-gi-hom-nay',
//                    'cdl_domain_id'  => '7',
//                    'cdl_check_page' => 0,
//                    'cdl_cate_id'    => '0',
//                    'cdl_page'       => '2',
//                    'cdl_status'     => '1',
//                  ],[
//                    'cdl_link'       => 'http://www.nauanngon123.com/nau-an-cuoi-tuan',
//                    'cdl_domain_id'  => '7',
//                    'cdl_check_page' => 0,
//                    'cdl_cate_id'    => '0',
//                    'cdl_page'       => '2',
//                    'cdl_status'     => '1',
//                  ],
//                    [
//                    'cdl_link'       => 'http://www.nauanngon123.com/mon-ngon-ha-noi',
//                    'cdl_domain_id'  => '7',
//                    'cdl_check_page' => 0,
//                    'cdl_cate_id'    => '0',
//                    'cdl_page'       => '2',
//                    'cdl_status'     => '1',
//                  ],
//                    [
//                        'cdl_link'       => 'http://webgiadinh.org/cam-nang/an-ngon-kheo-tay',
//                        'cdl_domain_id'  => '8',
//                        'cdl_check_page' => 1,
//                        'cdl_cate_id'    => '0',
//                        'cdl_page'       => '309',
//                        'cdl_status'     => '1',
//                    ],
//                        [
//                            'cdl_link'       => 'http://yeunoitro.net/nau-an',
//                            'cdl_domain_id'  => '9',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '302',
//                            'cdl_status'     => '1',
//                        ],
//                         [
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/phuong-phap-che-bien',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '50',
//                            'cdl_status'     => '1',
//                        ], [
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/cach-lam-banh',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '15',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/cach-lam-kem',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '3',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/mon-an-cho-be',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '10',
//                            'cdl_status'     => '1',
//                        ],
//                        [
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/do-an-sang',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '8',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/do-an-vat',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '22',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/do-uong',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '10',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/mon-nhau',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '7',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/mon-ngon-moi-ngay',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '69',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/mon-an-chay',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '2',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/mon-an-tet',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '6',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/mon-an-viet-nam',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '42',
//                            'cdl_status'     => '1',
//                        ],[
//                            'cdl_link'       => 'http://sotaynauan.com/chuyen-muc/mon-an-via-he',
//                            'cdl_domain_id'  => '10',
//                            'cdl_check_page' => 1,
//                            'cdl_cate_id'    => '0',
//                            'cdl_page'       => '6',
//                            'cdl_status'     => '1',
//                        ],
//                            [
//                                'cdl_link'       => 'https://monan9.com/chuyen-muc/mon-xao',
//                                'cdl_domain_id'  => '11',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '17',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'https://monan9.com/chuyen-muc/mon-chien',
//                                'cdl_domain_id'  => '11',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '9',
//                                'cdl_status'     => '1',
//                            ],[
//                                'cdl_link'       => 'https://monan9.com/chuyen-muc/mon-canh',
//                                'cdl_domain_id'  => '11',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '14',
//                                'cdl_status'     => '1',
//                            ],[
//                                'cdl_link'       => 'https://monan9.com/chuyen-muc/mon-kho',
//                                'cdl_domain_id'  => '11',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '8',
//                                'cdl_status'     => '1',
//                            ],[
//                                'cdl_link'       => 'https://monan9.com/chuyen-muc/mon-nom',
//                                'cdl_domain_id'  => '11',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '7',
//                                'cdl_status'     => '1',
//                            ],[
//                                'cdl_link'       => 'https://monan9.com/chuyen-muc/mon-nuong',
//                                'cdl_domain_id'  => '11',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '6',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://news.zing.vn/mon-ngon.html',
//                                'cdl_domain_id'  => '12',
//                                'cdl_check_page' => 0,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '1',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://news.zing.vn/mon-ngon',
//                                'cdl_domain_id'  => '12',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '20',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'https://agiadinh.net/category/cach-nau-an-ngon',
//                                'cdl_domain_id'  => '13',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '12',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://mongingon.com',
//                                'cdl_domain_id'  => '14',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '101',
//                                'cdl_status'     => '1',
//                            ],
//                             [
//                                'cdl_link'       => 'http://cachnauan.net/kien-thuc-am-thuc',
//                                'cdl_domain_id'  => '15',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '13',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://cachnauan.net/cach-nau-an',
//                                'cdl_domain_id'  => '15',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '62',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://cachnauan.net/cach-lam-banh',
//                                'cdl_domain_id'  => '15',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '17',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://cachnauan.net/cach-pha-che',
//                                'cdl_domain_id'  => '15',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '20',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://cachnauan.net/mon-an-dac-san',
//                                'cdl_domain_id'  => '15',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '11',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'https://nauankhongkho.com/category/mon-chinh',
//                                'cdl_domain_id'  => '16',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '111',
//                                'cdl_status'     => '1',
//                           ],
//                            [
//                                'cdl_link'       => 'https://nauankhongkho.com/category/mon-an-phu',
//                                'cdl_domain_id'  => '16',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '39',
//                                'cdl_status'     => '1',
//                           ],
//                            [
//                                'cdl_link'       => 'https://nauankhongkho.com/category/mon-an-vat',
//                                'cdl_domain_id'  => '16',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '35',
//                                'cdl_status'     => '1',
//                           ],
//                            [
//                                'cdl_link'       => 'https://nauankhongkho.com/category/cam-nang-huu-ich',
//                                'cdl_domain_id'  => '16',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '16',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'https://nauankhongkho.com/category/mon-chay',
//                                'cdl_domain_id'  => '16',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '7',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'https://nauankhongkho.com/category/trang-mieng',
//                                'cdl_domain_id'  => '16',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '7',
//                                'cdl_status'     => '1',
//                           ],
//                            [
//                                'cdl_link'       => 'https://nauankhongkho.com/category/suc-khoe-dinh-duong',
//                                'cdl_domain_id'  => '16',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '3',
//                                'cdl_status'     => '1',
//                           ],
//                            [
//                                'cdl_link'       => 'https://nauankhongkho.com/category/thuc-uong',
//                                'cdl_domain_id'  => '16',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '4',
//                                'cdl_status'     => '1',
//                           ],
//                            [
//                                'cdl_link'       => 'http://tapchiamthuc.com/am-thuc_1_49_',
//                                'cdl_domain_id'  => '17',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '8',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://tapchiamthuc.com/Mon-ngon-moi-ngay_1_7_',
//                                'cdl_domain_id'  => '17',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '11',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://tapchiamthuc.com/Nha-hang_1_1_',
//                                'cdl_domain_id'  => '17',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '9',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://tapchiamthuc.com/Thuc-pham_1_41_',
//                                'cdl_domain_id'  => '17',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '10',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://tapchiamthuc.com/The-gioi-am-thuc_1_2_',
//                                'cdl_domain_id'  => '17',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '10',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://tapchiamthuc.com/do-uong---Cocktail-_1_4_',
//                                'cdl_domain_id'  => '17',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '10',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://tapchiamthuc.com/Van-hoa-am-thuc_1_6_',
//                                'cdl_domain_id'  => '17',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '10',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://tapchiamthuc.com/Khong-gian-quan_1_40_',
//                                'cdl_domain_id'  => '17',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '8',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://tapchiamthuc.com/Cam-nang_1_8_',
//                                'cdl_domain_id'  => '17',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '10',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://www.tapchigiadinh.com.vn/News.aspx?cat=34&_Page_38',
//                                'cdl_domain_id'  => '18',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '102',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://lambanh365.com/cong-thuc-lam-banh',
//                                'cdl_domain_id'  => '19',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '109',
//                                'cdl_status'     => '1',
//                            ],
//                            [
//                                'cdl_link'       => 'http://lambanh365.com/chuyen-muc/mon-ngon',
//                                'cdl_domain_id'  => '19',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '5',
//                                'cdl_status'     => '1',
//                            ],
//                             [
//                                'cdl_link'       => 'http://amthuchanoi.org',
//                                'cdl_domain_id'  => '20',
//                                'cdl_check_page' => 1,
//                                'cdl_cate_id'    => '0',
//                                'cdl_page'       => '171',
//                                'cdl_status'     => '1',
//                            ],

        ];
    }
}