<?php
/**
 * Created by PhpStorm.
 * User: hung
 * Date: 08/03/17
 * Time: 01:56
 */

namespace App\Models\Events;


use App\Repositories\BaseRepository;

class EloquentEvent extends BaseRepository implements EventRepository
{
    public function __construct(Event $event)
    {
        $this->model = $event;
    }

    public function getListEventPaginate($filter, $sort, $limit=30)
    {
        return $this->getAll($filter, $sort, $limit);
    }

    public function storeData($attributes)
    {
        return parent::storeData($attributes); // TODO: Change the autogenerated stub
    }

    public function updateByField($id, $field, $otherValue = '')
    {
        return parent::updateByField($id, $field, $otherValue); // TODO: Change the autogenerated stub
    }

    public function updateById($id, $data)
    {
        return parent::updateById($id, $data); // TODO: Change the autogenerated stub
    }

    public function attachEventCate($instance, $categoryId)
    {
        return $instance->attach($categoryId);
    }

    public function syncEventCate($instance, $categoryId)
    {
        return $instance->sync($categoryId);
    }
}